// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_ckVL2PINTpc6RFLXQ2gPnCuZfGs0wA',
    appId: '1:126169545111:web:1368e1eece81aaa813acd2',
    messagingSenderId: '126169545111',
    projectId: 'product-store-26f3e',
    authDomain: 'product-store-26f3e.firebaseapp.com',
    storageBucket: 'product-store-26f3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8_POtx6UzJbLS_JaLI5LV42KrtdPaxw',
    appId: '1:126169545111:android:deea761e6ca9b11513acd2',
    messagingSenderId: '126169545111',
    projectId: 'product-store-26f3e',
    storageBucket: 'product-store-26f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERfSlVy4WHiRs1AUzFhyHXDnt9h8AEtA',
    appId: '1:126169545111:ios:e7a5df2c2a6a58d913acd2',
    messagingSenderId: '126169545111',
    projectId: 'product-store-26f3e',
    storageBucket: 'product-store-26f3e.appspot.com',
    iosBundleId: 'com.mohammedek.applications.loginCourseApp',
  );
}
